package bsmgg.bsmgg_backend.global.mapping;

import org.springframework.stereotype.Service;

import java.util.HashMap;
import java.util.Map;

@Service
public class MappingService {

    private Map<Integer, String> perkIdMap;
    private Map<String, String> perkNameMap;
    private Map<Integer, String> spellIdMap;
    private Map<String, String> spellNameMap;
    private Map<Integer, String> queueMap;
    private Map<String, String> champMap;
    private Map<Integer, String> itemMap;

    public MappingService() {
        initPerkMap();
        initSpellMap();
        initQueueMap();
        initChampMap();
        initItemMap();
    }

    private void initItemMap() {
        itemMap = new HashMap<>();

        itemMap.put(1001, "장화");
        itemMap.put(1004, "요정의 부적");
        itemMap.put(1006, "원기 회복의 구슬");
        itemMap.put(1011, "거인의 허리띠");
        itemMap.put(1018, "민첩성의 망토");
        itemMap.put(1026, "방출의 마법봉");
        itemMap.put(1027, "사파이어 수정");
        itemMap.put(1028, "루비 수정");
        itemMap.put(1029, "천 갑옷");
        itemMap.put(1031, "쇠사슬 조끼");
        itemMap.put(1033, "마법무효화의 망토");
        itemMap.put(1035, "잉걸불 칼");
        itemMap.put(1036, "롱소드");
        itemMap.put(1037, "곡괭이");
        itemMap.put(1038, "B.F. 대검");
        itemMap.put(1039, "빗발칼날");
        itemMap.put(1040, "흑요석 검");
        itemMap.put(1042, "단검");
        itemMap.put(1043, "곡궁");
        itemMap.put(1052, "증폭의 고서");
        itemMap.put(1053, "흡혈의 낫");
        itemMap.put(1054, "도란의 방패");
        itemMap.put(1055, "도란의 검");
        itemMap.put(1056, "도란의 반지");
        itemMap.put(1057, "음전자 망토");
        itemMap.put(1058, "쓸데없이 큰 지팡이");
        itemMap.put(1082, "암흑의 인장");
        itemMap.put(1083, "수확의 낫");
        itemMap.put(1101, "새끼 화염발톱");
        itemMap.put(1102, "새끼 바람돌이");
        itemMap.put(1103, "새끼 이끼쿵쿵이");
        itemMap.put(1104, "전령의 눈");
        itemMap.put(1500, "관통 탄환");
        itemMap.put(1501, "요새화");
        itemMap.put(1502, "이중 갑옷");
        itemMap.put(1503, "파수꾼의 눈");
        itemMap.put(1504, "수호자");
        itemMap.put(1506, "이중 갑옷");
        itemMap.put(1507, "과충전");
        itemMap.put(1508, "방탄 양말");
        itemMap.put(1509, "체질");
        itemMap.put(1510, "특이 체질");
        itemMap.put(1511, "슈퍼 메크 방어구");
        itemMap.put(1512, "슈퍼 메크 전력장");
        itemMap.put(1515, "포탑 방패");
        itemMap.put(1516, "구조물 현상금");
        itemMap.put(1517, "구조물 현상금");
        itemMap.put(1518, "구조물 현상금");
        itemMap.put(1519, "구조물 현상금");
        itemMap.put(1520, "과충전HA");
        itemMap.put(1521, "요새화");
        itemMap.put(1522, "포탑 강화");
        itemMap.put(2003, "체력 물약");
        itemMap.put(2010, "굳건한 의지의 완전한 비스킷");
        itemMap.put(2015, "키르히아이스의 파편");
        itemMap.put(2019, "강철 인장");
        itemMap.put(2020, "야수화");
        itemMap.put(2021, "땅굴 채굴기");
        itemMap.put(2022, "빛나는 티끌");
        itemMap.put(2031, "충전형 물약");
        itemMap.put(2033, "부패 물약");
        itemMap.put(2049, "수호자의 부적");
        itemMap.put(2050, "수호자의 장막");
        itemMap.put(2051, "수호자의 뿔피리");
        itemMap.put(2052, "포로 간식");
        itemMap.put(2055, "제어 와드");
        itemMap.put(2056, "투명 와드");
        itemMap.put(2065, "슈렐리아의 군가");
        itemMap.put(2138, "강철의 영약");
        itemMap.put(2139, "마법의 영약");
        itemMap.put(2140, "분노의 영약");
        itemMap.put(2141, "카파 주스");
        itemMap.put(2142, "힘의 주스");
        itemMap.put(2143, "활력의 주스");
        itemMap.put(2144, "가속의 주스");
        itemMap.put(2145, "행운의 주사위");
        itemMap.put(2150, "숙련의 영약");
        itemMap.put(2151, "탐욕의 영약");
        itemMap.put(2152, "힘의 영약");
        itemMap.put(2403, "미니언 해체분석기");
        itemMap.put(2420, "추적자의 팔목 보호대");
        itemMap.put(2421, "부서진 팔목 보호대");
        itemMap.put(2422, "약간 신비한 신발");
        itemMap.put(2501, "지배자의 피갑옷");
        itemMap.put(2502, "끝없는 절망");
        itemMap.put(2503, "어둠불꽃 횃불");
        itemMap.put(2504, "케이닉 루컨");
        itemMap.put(2508, "운명의 재");
        itemMap.put(3001, "저녁갑주");
        itemMap.put(3002, "개척자");
        itemMap.put(3003, "대천사의 지팡이");
        itemMap.put(3004, "마나무네");
        itemMap.put(3005, "유령 배회자");
        itemMap.put(3006, "광전사의 군화");
        itemMap.put(3009, "신속의 장화");
        itemMap.put(3010, "공생형 밑창");
        itemMap.put(3011, "화학공학 부패기");
        itemMap.put(3012, "축복의 성배");
        itemMap.put(3013, "하나 된 영혼");
        itemMap.put(3020, "마법사의 신발");
        itemMap.put(3023, "생명의 샘 펜던트");
        itemMap.put(3024, "얼음 방패");
        itemMap.put(3026, "수호 천사");
        itemMap.put(3031, "무한의 대검");
        itemMap.put(3032, "윤 탈 야생화살");
        itemMap.put(3033, "필멸자의 운명");
        itemMap.put(3035, "최후의 속삭임");
        itemMap.put(3036, "도미닉 경의 인사");
        itemMap.put(3039, "아트마의 심판");
        itemMap.put(3040, "대천사의 포옹");
        itemMap.put(3041, "메자이의 영혼약탈자");
        itemMap.put(3042, "무라마나");
        itemMap.put(3044, "탐식의 망치");
        itemMap.put(3046, "유령 무희");
        itemMap.put(3047, "판금 장화");
        itemMap.put(3050, "지크의 융합");
        itemMap.put(3051, "온기가 필요한 자의 도끼");
        itemMap.put(3053, "스테락의 도전");
        itemMap.put(3057, "광휘의 검");
        itemMap.put(3065, "정령의 형상");
        itemMap.put(3066, "비상의 월갑");
        itemMap.put(3067, "점화석");
        itemMap.put(3068, "태양불꽃 방패");
        itemMap.put(3070, "여신의 눈물");
        itemMap.put(3071, "칠흑의 양날 도끼");
        itemMap.put(3072, "피바라기");
        itemMap.put(3073, "실험적 마공학판");
        itemMap.put(3074, "굶주린 히드라");
        itemMap.put(3075, "가시 갑옷");
        itemMap.put(3076, "덤불 조끼");
        itemMap.put(3077, "티아맷");
        itemMap.put(3078, "삼위일체");
        itemMap.put(3082, "파수꾼의 갑옷");
        itemMap.put(3083, "워모그의 갑옷");
        itemMap.put(3084, "강철심장");
        itemMap.put(3085, "루난의 허리케인");
        itemMap.put(3086, "열정의 검");
        itemMap.put(3087, "스태틱의 단검");
        itemMap.put(3089, "라바돈의 죽음모자");
        itemMap.put(3091, "마법사의 최후");
        itemMap.put(3094, "고속 연사포");
        itemMap.put(3095, "폭풍갈퀴");
        itemMap.put(3100, "리치베인");
        itemMap.put(3102, "밴시의 장막");
        itemMap.put(3105, "군단의 방패");
        itemMap.put(3107, "구원");
        itemMap.put(3108, "악마의 마법서");
        itemMap.put(3109, "기사의 맹세");
        itemMap.put(3110, "얼어붙은 심장");
        itemMap.put(3111, "헤르메스의 발걸음");
        itemMap.put(3112, "수호자의 보주");
        itemMap.put(3113, "에테르 환영");
        itemMap.put(3114, "금지된 우상");
        itemMap.put(3115, "내셔의 이빨");
        itemMap.put(3116, "라일라이의 수정홀");
        itemMap.put(3117, "기동력의 장화");
        itemMap.put(3118, "악의");
        itemMap.put(3119, "혹한의 손길");
        itemMap.put(3121, "종말의 겨울");
        itemMap.put(3123, "처형인의 대검");
        itemMap.put(3124, "구인수의 격노검");
        itemMap.put(3128, "죽음불꽃 손아귀");
        itemMap.put(3131, "신성의 검");
        itemMap.put(3133, "콜필드의 전투 망치");
        itemMap.put(3134, "톱날 단검");
        itemMap.put(3135, "공허의 지팡이");
        itemMap.put(3137, "무덤꽃");
        itemMap.put(3139, "헤르메스의 시미터");
        itemMap.put(3140, "수은 장식띠");
        itemMap.put(3142, "요우무의 유령검");
        itemMap.put(3143, "란두인의 예언");
        itemMap.put(3144, "정찰병의 새총");
        itemMap.put(3145, "마법공학 교류 발전기");
        itemMap.put(3146, "마법공학 총검");
        itemMap.put(3147, "기괴한 가면");
        itemMap.put(3152, "마법공학 로켓 벨트");
        itemMap.put(3153, "몰락한 왕의 검");
        itemMap.put(3155, "주문포식자");
        itemMap.put(3156, "맬모셔스의 아귀");
        itemMap.put(3157, "존야의 모래시계");
        itemMap.put(3158, "명석함의 아이오니아 장화");
        itemMap.put(3161, "쇼진의 창");
        itemMap.put(3165, "모렐로노미콘");
        itemMap.put(3172, "서풍");
        itemMap.put(3177, "수호자의 검");
        itemMap.put(3179, "그림자 검");
        itemMap.put(3181, "선체파괴자");
        itemMap.put(3184, "수호자의 망치");
        itemMap.put(3190, "강철의 솔라리 펜던트");
        itemMap.put(3193, "가고일 돌갑옷");
        itemMap.put(3211, "망령의 두건");
        itemMap.put(3222, "미카엘의 축복");
        itemMap.put(3302, "경계");
        itemMap.put(3330, "허수아비");
        itemMap.put(3340, "투명 와드");
        itemMap.put(3348, "비전 탐지기");
        itemMap.put(3349, "광휘의 특이점");
        itemMap.put(3363, "망원형 개조");
        itemMap.put(3364, "예언자의 렌즈");
        itemMap.put(3400, "수당");
        itemMap.put(3430, "파멸의식 고서");
        itemMap.put(3504, "불타는 향로");
        itemMap.put(3508, "정수 약탈자");
        itemMap.put(3513, "전령의 눈");
        itemMap.put(3599, "칼리스타의 칠흑의 창");
        itemMap.put(3600, "칼리스타의 칠흑의 창");
        itemMap.put(3742, "망자의 갑옷");
        itemMap.put(3748, "거대한 히드라");
        itemMap.put(3801, "수정 팔 보호구");
        itemMap.put(3802, "사라진 양피지");
        itemMap.put(3803, "억겁의 카탈리스트");
        itemMap.put(3814, "밤의 끝자락");
        itemMap.put(3850, "주문도둑의 검");
        itemMap.put(3851, "얼음 송곳니");
        itemMap.put(3853, "얼음 정수의 파편");
        itemMap.put(3854, "강철 어깨 보호대");
        itemMap.put(3855, "룬 강철 어깨 갑옷");
        itemMap.put(3857, "화이트록의 갑옷");
        itemMap.put(3858, "고대유물 방패");
        itemMap.put(3859, "타곤 산의 방패");
        itemMap.put(3860, "타곤 산의 방벽");
        itemMap.put(3862, "영혼의 낫");
        itemMap.put(3863, "해로윙 초승달낫");
        itemMap.put(3864, "검은 안개 낫");
        itemMap.put(3865, "세계 지도집");
        itemMap.put(3866, "룬 나침반");
        itemMap.put(3867, "세계의 결실");
        itemMap.put(3869, "천상의 이의");
        itemMap.put(3870, "꿈 생성기");
        itemMap.put(3871, "자자크의 세계가시");
        itemMap.put(3876, "태양의 썰매");
        itemMap.put(3877, "피의 노래");
        itemMap.put(3901, "가차없는 포격");
        itemMap.put(3902, "죽음의 여신");
        itemMap.put(3903, "사기진작");
        itemMap.put(3916, "망각의 구");
        itemMap.put(4003, "생명선");
        itemMap.put(4004, "망령 해적검");
        itemMap.put(4005, "제국의 명령");
        itemMap.put(4010, "핏빛 저주");
        itemMap.put(4011, "꽃피는 새벽의 검");
        itemMap.put(4012, "죄악 포식자");
        itemMap.put(4013, "번개 끈");
        itemMap.put(4014, "얼어붙은 망치");
        itemMap.put(4015, "당혹");
        itemMap.put(4016, "무언의 서약");
        itemMap.put(4017, "지옥불 손도끼");
        itemMap.put(4401, "대자연의 힘");
        itemMap.put(4402, "활력증진의 펜던트");
        itemMap.put(4403, "황금 뒤집개");
        itemMap.put(4628, "지평선의 초점");
        itemMap.put(4629, "우주의 추진력");
        itemMap.put(4630, "역병의 보석");
        itemMap.put(4632, "신록의 장벽");
        itemMap.put(4633, "균열 생성기");
        itemMap.put(4635, "흡수의 시선");
        itemMap.put(4636, "밤의 수확자");
        itemMap.put(4637, "악마의 포옹");
        itemMap.put(4638, "감시하는 와드석");
        itemMap.put(4641, "고무의 와드석");
        itemMap.put(4642, "밴들유리 거울");
        itemMap.put(4643, "경계의 와드석");
        itemMap.put(4644, "부서진 여왕의 왕관");
        itemMap.put(4645, "그림자불꽃");
        itemMap.put(4646, "폭풍 쇄도");
        itemMap.put(6029, "강철가시 채찍");
        itemMap.put(6035, "은빛 여명");
        itemMap.put(6333, "죽음의 무도");
        itemMap.put(6609, "화공 펑크 사슬검");
        itemMap.put(6610, "갈라진 하늘");
        itemMap.put(6616, "흐르는 물의 지팡이");
        itemMap.put(6617, "월석 재생기");
        itemMap.put(6620, "헬리아의 메아리");
        itemMap.put(6621, "새벽심장");
        itemMap.put(6630, "선혈포식자");
        itemMap.put(6631, "발걸음 분쇄기");
        itemMap.put(6632, "신성한 파괴자");
        itemMap.put(6653, "리안드리의 고통");
        itemMap.put(6655, "루덴의 동반자");
        itemMap.put(6656, "만년서리");
        itemMap.put(6657, "영겁의 지팡이");
        itemMap.put(6660, "바미의 불씨");
        itemMap.put(6662, "얼어붙은 건틀릿");
        itemMap.put(6664, "공허한 광휘");
        itemMap.put(6665, "해신 작쇼");
        itemMap.put(6667, "광휘의 미덕");
        itemMap.put(6670, "절정의 화살");
        itemMap.put(6671, "돌풍");
        itemMap.put(6672, "크라켄 학살자");
        itemMap.put(6673, "불멸의 철갑궁");
        itemMap.put(6675, "나보리 명멸검");
        itemMap.put(6676, "징수의 총");
        itemMap.put(6677, "분노의 칼");
        itemMap.put(6690, "꽁지깃");
        itemMap.put(6691, "드락사르의 황혼검");
        itemMap.put(6692, "월식");
        itemMap.put(6693, "자객의 발톱");
        itemMap.put(6694, "세릴다의 원한");
        itemMap.put(6695, "독사의 송곳니");
        itemMap.put(6696, "원칙의 원형낫");
        itemMap.put(6697, "오만");
        itemMap.put(6698, "불경한 히드라");
        itemMap.put(6699, "벼락폭풍검");
        itemMap.put(6700, "라코어의 방패");
        itemMap.put(6701, "기회");
        itemMap.put(7000, "암살자의 발톱");
        itemMap.put(7001, "천체 정렬");
        itemMap.put(7002, "드락사르의 암흑검");
        itemMap.put(7003, "라바돈의 죽음왕관");
        itemMap.put(7004, "다수의 원한");
        itemMap.put(7005, "얼어붙은 주먹");
        itemMap.put(7006, "태풍");
        itemMap.put(7007, "선풍검");
        itemMap.put(7008, "영혼의 평정");
        itemMap.put(7009, "이케시아의 저주");
        itemMap.put(7010, "어스름의 기원");
        itemMap.put(7011, "업그레이드 비행팩");
        itemMap.put(7012, "리안드리의 슬픔");
        itemMap.put(7013, "무기의 위력");
        itemMap.put(7014, "영원한 겨울");
        itemMap.put(7015, "무한한 허기");
        itemMap.put(7016, "몽상파쇄자");
        itemMap.put(7017, "신성시해자");
        itemMap.put(7018, "무한한 삼위일체");
        itemMap.put(7019, "황금 새벽의 유물함");
        itemMap.put(7020, "슈렐리아의 진혼곡");
        itemMap.put(7021, "성운 투척기");
        itemMap.put(7022, "확실성");
        itemMap.put(7023, "별의 균형");
        itemMap.put(7024, "중단");
        itemMap.put(7025, "레비아탄");
        itemMap.put(7026, "무언의 기생갑");
        itemMap.put(7027, "태고의 새벽");
        itemMap.put(7028, "무한 융합");
        itemMap.put(7029, "요우무의 각성");
        itemMap.put(7030, "들끓는 슬픔");
        itemMap.put(7031, "궁극의 검");
        itemMap.put(7032, "명멸");
        itemMap.put(7033, "비명을 지르는 도시의 외침");
        itemMap.put(7034, "떠도는 희망");
        itemMap.put(7035, "해오름");
        itemMap.put(7036, "터.보.추.진.기");
        itemMap.put(7037, "흑요석 양날 도끼");
        itemMap.put(7038, "쇼진의 결의");
        itemMap.put(7039, "천상의 몰락");
        itemMap.put(7040, "폭풍의 눈");
        itemMap.put(7041, "쓰러진 용의 제물");
        itemMap.put(7042, "남작의 선물");
        itemMap.put(7050, "갱플랭크 Placeholder");
        itemMap.put(8001, "증오의 사슬");
        itemMap.put(8020, "심연의 가면");
        itemMap.put(126697, "오만");
        itemMap.put(127008, "영혼의 평정");
        itemMap.put(220000, "추가 능력치");
        itemMap.put(220001, "전설 전사 아이템");
        itemMap.put(220002, "전설 원거리 딜러 아이템");
        itemMap.put(220003, "전설 암살자 아이템");
        itemMap.put(220004, "전설 마법사 아이템");
        itemMap.put(220005, "전설 탱커 아이템");
        itemMap.put(220006, "전설 서포터 아이템");
        itemMap.put(220007, "프리즘 아이템");
        itemMap.put(221011, "거인의 허리띠");
        itemMap.put(221026, "방출의 마법봉");
        itemMap.put(221031, "쇠사슬 조끼");
        itemMap.put(221038, "B.F. 대검");
        itemMap.put(221043, "곡궁");
        itemMap.put(221053, "흡혈의 낫");
        itemMap.put(221057, "음전자 망토");
        itemMap.put(221058, "쓸데없이 큰 지팡이");
        itemMap.put(222022, "빛나는 티끌");
        itemMap.put(222051, "수호자의 뿔피리");
        itemMap.put(222065, "슈렐리아의 군가");
        itemMap.put(222141, "카파 주스");
        itemMap.put(222502, "끝없는 절망");
        itemMap.put(222503, "어둠불꽃 횃불");
        itemMap.put(222504, "케이닉 루컨");
        itemMap.put(223001, "저녁갑주");
        itemMap.put(223002, "개척자");
        itemMap.put(223003, "대천사의 지팡이");
        itemMap.put(223004, "마나무네");
        itemMap.put(223005, "유령 배회자");
        itemMap.put(223006, "광전사의 군화");
        itemMap.put(223009, "신속의 장화");
        itemMap.put(223011, "화학공학 부패기");
        itemMap.put(223020, "마법사의 신발");
        itemMap.put(223026, "수호 천사");
        itemMap.put(223031, "무한의 대검");
        itemMap.put(223032, "윤 탈 야생화살");
        itemMap.put(223033, "필멸자의 운명");
        itemMap.put(223036, "도미닉 경의 인사");
        itemMap.put(223039, "아트마의 심판");
        itemMap.put(223040, "대천사의 포옹");
        itemMap.put(223042, "무라마나");
        itemMap.put(223046, "유령 무희");
        itemMap.put(223047, "판금 장화");
        itemMap.put(223050, "지크의 융합");
        itemMap.put(223053, "스테락의 도전");
        itemMap.put(223057, "광휘의 검");
        itemMap.put(223065, "정령의 형상");
        itemMap.put(223067, "점화석");
        itemMap.put(223068, "태양불꽃 방패");
        itemMap.put(223071, "칠흑의 양날 도끼");
        itemMap.put(223072, "피바라기");
        itemMap.put(223073, "실험적 마공학판");
        itemMap.put(223074, "굶주린 히드라");
        itemMap.put(223075, "가시 갑옷");
        itemMap.put(223078, "삼위일체");
        itemMap.put(223084, "강철심장");
        itemMap.put(223085, "루난의 허리케인");
        itemMap.put(223087, "스태틱의 단검");
        itemMap.put(223089, "라바돈의 죽음모자");
        itemMap.put(223091, "마법사의 최후");
        itemMap.put(223094, "고속 연사포");
        itemMap.put(223095, "폭풍갈퀴");
        itemMap.put(223100, "리치베인");
        itemMap.put(223102, "밴시의 장막");
        itemMap.put(223105, "군단의 방패");
        itemMap.put(223107, "구원");
        itemMap.put(223109, "기사의 맹세");
        itemMap.put(223110, "얼어붙은 심장");
        itemMap.put(223111, "헤르메스의 발걸음");
        itemMap.put(223112, "수호자의 보주");
        itemMap.put(223115, "내셔의 이빨");
        itemMap.put(223116, "라일라이의 수정홀");
        itemMap.put(223118, "악의");
        itemMap.put(223119, "혹한의 손길");
        itemMap.put(223121, "종말의 겨울");
        itemMap.put(223124, "구인수의 격노검");
        itemMap.put(223135, "공허의 지팡이");
        itemMap.put(223137, "무덤꽃");
        itemMap.put(223139, "헤르메스의 시미터");
        itemMap.put(223142, "요우무의 유령검");
        itemMap.put(223143, "란두인의 예언");
        itemMap.put(223146, "마법공학 총검");
        itemMap.put(223152, "마법공학 로켓 벨트");
        itemMap.put(223153, "몰락한 왕의 검");
        itemMap.put(223156, "맬모셔스의 아귀");
        itemMap.put(223157, "존야의 모래시계");
        itemMap.put(223158, "명석함의 아이오니아 장화");
        itemMap.put(223161, "쇼진의 창");
        itemMap.put(223165, "모렐로노미콘");
        itemMap.put(223172, "서풍");
        itemMap.put(223177, "수호자의 검");
        itemMap.put(223181, "선체파괴자");
        itemMap.put(223184, "수호자의 망치");
        itemMap.put(223185, "수호자의 단검");
        itemMap.put(223190, "강철의 솔라리 펜던트");
        itemMap.put(223193, "가고일 돌갑옷");
        itemMap.put(223222, "미카엘의 축복");
        itemMap.put(223302, "경계");
        itemMap.put(223504, "불타는 향로");
        itemMap.put(223508, "정수 약탈자");
        itemMap.put(223742, "망자의 갑옷");
        itemMap.put(223748, "거대한 히드라");
        itemMap.put(223814, "밤의 끝자락");
        itemMap.put(224004, "망령 해적검");
        itemMap.put(224005, "제국의 명령");
        itemMap.put(224401, "대자연의 힘");
        itemMap.put(224403, "황금 뒤집개");
        itemMap.put(224628, "지평선의 초점");
        itemMap.put(224629, "우주의 추진력");
        itemMap.put(224633, "균열 생성기");
        itemMap.put(224636, "밤의 수확자");
        itemMap.put(224637, "악마의 포옹");
        itemMap.put(224644, "부서진 여왕의 왕관");
        itemMap.put(224645, "그림자불꽃");
        itemMap.put(224646, "폭풍 쇄도");
        itemMap.put(226035, "은빛 여명");
        itemMap.put(226333, "죽음의 무도");
        itemMap.put(226609, "화공 펑크 사슬검");
        itemMap.put(226610, "갈라진 하늘");
        itemMap.put(226616, "흐르는 물의 지팡이");
        itemMap.put(226617, "월석 재생기");
        itemMap.put(226620, "헬리아의 메아리");
        itemMap.put(226621, "새벽심장");
        itemMap.put(226630, "선혈포식자");
        itemMap.put(226631, "발걸음 분쇄기");
        itemMap.put(226632, "신성한 파괴자");
        itemMap.put(226653, "리안드리의 고통");
        itemMap.put(226655, "루덴의 동반자");
        itemMap.put(226656, "만년서리");
        itemMap.put(226657, "영겁의 지팡이");
        itemMap.put(226662, "얼어붙은 건틀릿");
        itemMap.put(226664, "공허한 광휘");
        itemMap.put(226665, "해신 작쇼");
        itemMap.put(226667, "광휘의 미덕");
        itemMap.put(226671, "돌풍");
        itemMap.put(226672, "크라켄 학살자");
        itemMap.put(226673, "불멸의 철갑궁");
        itemMap.put(226675, "나보리 명멸검");
        itemMap.put(226676, "징수의 총");
        itemMap.put(226691, "드락사르의 황혼검");
        itemMap.put(226692, "월식");
        itemMap.put(226693, "자객의 발톱");
        itemMap.put(226694, "세릴다의 원한");
        itemMap.put(226695, "독사의 송곳니");
        itemMap.put(226696, "원칙의 원형낫");
        itemMap.put(226697, "오만");
        itemMap.put(226698, "불경한 히드라");
        itemMap.put(226699, "벼락폭풍검");
        itemMap.put(226701, "기회");
        itemMap.put(227001, "천체 정렬");
        itemMap.put(227002, "드락사르의 암흑검");
        itemMap.put(227005, "얼어붙은 주먹");
        itemMap.put(227006, "태풍");
        itemMap.put(227009, "이케시아의 저주");
        itemMap.put(227010, "어스름의 기원");
        itemMap.put(227011, "업그레이드 비행팩");
        itemMap.put(227012, "리안드리의 슬픔");
        itemMap.put(227013, "무기의 위력");
        itemMap.put(227014, "영원한 겨울");
        itemMap.put(227015, "무한한 허기");
        itemMap.put(227016, "몽상파쇄자");
        itemMap.put(227017, "신성시해자");
        itemMap.put(227018, "무한한 삼위일체");
        itemMap.put(227019, "황금 새벽의 유물함");
        itemMap.put(227020, "슈렐리아의 진혼곡");
        itemMap.put(227021, "성운 투척기");
        itemMap.put(227023, "별의 균형");
        itemMap.put(227024, "중단");
        itemMap.put(227025, "레비아탄");
        itemMap.put(227026, "무언의 기생갑");
        itemMap.put(227027, "태고의 새벽");
        itemMap.put(227028, "무한 융합");
        itemMap.put(227029, "요우무의 각성");
        itemMap.put(227030, "들끓는 슬픔");
        itemMap.put(227031, "궁극의 검");
        itemMap.put(227032, "명멸");
        itemMap.put(227033, "비명을 지르는 도시의 외침");
        itemMap.put(228001, "증오의 사슬");
        itemMap.put(228002, "우글렛의 마녀 모자");
        itemMap.put(228003, "죽음의 검");
        itemMap.put(228004, "적응형 투구");
        itemMap.put(228005, "흑요석 양날 도끼");
        itemMap.put(228006, "핏빛 칼날");
        itemMap.put(228008, "룬 글레이브");
        itemMap.put(228020, "심연의 가면");
        itemMap.put(443054, "흑강철 발톱");
        itemMap.put(443055, "질책");
        itemMap.put(443056, "불사대마왕의 왕관");
        itemMap.put(443058, "용암의 방패");
        itemMap.put(443059, "별빛밤 망토");
        itemMap.put(443060, "신성의 검");
        itemMap.put(443061, "엔트로피의 힘");
        itemMap.put(443062, "핏빛 선물");
        itemMap.put(443063, "일라이자의 기적");
        itemMap.put(443064, "승천의 부적");
        itemMap.put(443069, "불귀신");
        itemMap.put(443079, "터보 화공 탱크");
        itemMap.put(443193, "가고일 돌갑옷");
        itemMap.put(444636, "밤의 수확자");
        itemMap.put(444637, "악마의 포옹");
        itemMap.put(444644, "부서진 여왕의 왕관");
        itemMap.put(446632, "신성한 파괴자");
        itemMap.put(446656, "만년서리");
        itemMap.put(446667, "광휘의 미덕");
        itemMap.put(446671, "돌풍");
        itemMap.put(446691, "드락사르의 황혼검");
        itemMap.put(446693, "자객의 발톱");
        itemMap.put(447100, "신기루 검");
        itemMap.put(447101, "도박꾼의 칼날");
        itemMap.put(447102, "현실 균열");
        itemMap.put(447103, "혈마법사의 투구");
        itemMap.put(447104, "활력증진의 펜던트");
        itemMap.put(447105, "창공의 서약");
        itemMap.put(447106, "용의 심장");
        itemMap.put(447107, "참수자");
        itemMap.put(447108, "룬 조각기");
        itemMap.put(447109, "잔혹 행위");
        itemMap.put(447110, "달빛 마법검");
        itemMap.put(447111, "지배자의 피갑옷");
        itemMap.put(447112, "살점포식자");
        itemMap.put(447113, "폭발의 구");
    }

    private void initChampMap() {
        champMap = new HashMap<>();

        champMap.put("Aatrox", "아트록스");
        champMap.put("Ahri", "아리");
        champMap.put("Akali", "아칼리");
        champMap.put("Akshan", "아크샨");
        champMap.put("Alistar", "알리스타");
        champMap.put("Amumu", "아무무");
        champMap.put("Anivia", "애니비아");
        champMap.put("Annie", "애니");
        champMap.put("Aphelios", "아펠리오스");
        champMap.put("Ashe", "애쉬");
        champMap.put("AurelionSol", "아우렐리온 솔");
        champMap.put("Azir", "아지르");
        champMap.put("Bard", "바드");
        champMap.put("Belveth", "벨베스");
        champMap.put("Blitzcrank", "블리츠크랭크");
        champMap.put("Brand", "브랜드");
        champMap.put("Braum", "브라움");
        champMap.put("Briar", "브라이어");
        champMap.put("Caitlyn", "케이틀린");
        champMap.put("Camille", "카밀");
        champMap.put("Cassiopeia", "카시오페아");
        champMap.put("Chogath", "초가스");
        champMap.put("Corki", "코르키");
        champMap.put("Darius", "다리우스");
        champMap.put("Diana", "다이애나");
        champMap.put("Draven", "드레이븐");
        champMap.put("DrMundo", "문도 박사");
        champMap.put("Ekko", "에코");
        champMap.put("Elise", "엘리스");
        champMap.put("Evelynn", "이블린");
        champMap.put("Ezreal", "이즈리얼");
        champMap.put("Fiddlesticks", "피들스틱");
        champMap.put("Fiora", "피오라");
        champMap.put("Fizz", "피즈");
        champMap.put("Galio", "갈리오");
        champMap.put("Gangplank", "갱플랭크");
        champMap.put("Garen", "가렌");
        champMap.put("Gnar", "나르");
        champMap.put("Gragas", "그라가스");
        champMap.put("Graves", "그레이브즈");
        champMap.put("Gwen", "그웬");
        champMap.put("Hecarim", "헤카림");
        champMap.put("Heimerdinger", "하이머딩거");
        champMap.put("Hwei", "흐웨이");
        champMap.put("Illaoi", "일라오이");
        champMap.put("Irelia", "이렐리아");
        champMap.put("Ivern", "아이번");
        champMap.put("Janna", "잔나");
        champMap.put("JarvanIV", "자르반 4세");
        champMap.put("Jax", "잭스");
        champMap.put("Jayce", "제이스");
        champMap.put("Jhin", "진");
        champMap.put("Jinx", "징크스");
        champMap.put("Kaisa", "카이사");
        champMap.put("Kalista", "칼리스타");
        champMap.put("Karma", "카르마");
        champMap.put("Karthus", "카서스");
        champMap.put("Kassadin", "카사딘");
        champMap.put("Katarina", "카타리나");
        champMap.put("Kayle", "케일");
        champMap.put("Kayn", "케인");
        champMap.put("Kennen", "케넨");
        champMap.put("Khazix", "카직스");
        champMap.put("Kindred", "킨드레드");
        champMap.put("Kled", "클레드");
        champMap.put("KogMaw", "코그모");
        champMap.put("KSante", "크산테");
        champMap.put("Leblanc", "르블랑");
        champMap.put("LeeSin", "리 신");
        champMap.put("Leona", "레오나");
        champMap.put("Lillia", "릴리아");
        champMap.put("Lissandra", "리산드라");
        champMap.put("Lucian", "루시안");
        champMap.put("Lulu", "룰루");
        champMap.put("Lux", "럭스");
        champMap.put("Malphite", "말파이트");
        champMap.put("Malzahar", "말자하");
        champMap.put("Maokai", "마오카이");
        champMap.put("MasterYi", "마스터 이");
        champMap.put("Milio", "밀리오");
        champMap.put("MissFortune", "미스 포츈");
        champMap.put("MonkeyKing", "오공");
        champMap.put("Mordekaiser", "모데카이저");
        champMap.put("Morgana", "모르가나");
        champMap.put("Naafiri", "나피리");
        champMap.put("Nami", "나미");
        champMap.put("Nasus", "나서스");
        champMap.put("Nautilus", "노틸러스");
        champMap.put("Neeko", "니코");
        champMap.put("Nidalee", "니달리");
        champMap.put("Nilah", "닐라");
        champMap.put("Nocturne", "녹턴");
        champMap.put("Nunu", "누누와 윌럼프");
        champMap.put("Olaf", "올라프");
        champMap.put("Orianna", "오리아나");
        champMap.put("Ornn", "오른");
        champMap.put("Pantheon", "판테온");
        champMap.put("Poppy", "뽀삐");
        champMap.put("Pyke", "파이크");
        champMap.put("Qiyana", "키아나");
        champMap.put("Quinn", "퀸");
        champMap.put("Rakan", "라칸");
        champMap.put("Rammus", "람머스");
        champMap.put("RekSai", "렉사이");
        champMap.put("Rell", "렐");
        champMap.put("Renata", "레나타 글라스크");
        champMap.put("Renekton", "레넥톤");
        champMap.put("Rengar", "렝가");
        champMap.put("Riven", "리븐");
        champMap.put("Rumble", "럼블");
        champMap.put("Ryze", "라이즈");
        champMap.put("Samira", "사미라");
        champMap.put("Sejuani", "세주아니");
        champMap.put("Senna", "세나");
        champMap.put("Seraphine", "세라핀");
        champMap.put("Sett", "세트");
        champMap.put("Shaco", "샤코");
        champMap.put("Shen", "쉔");
        champMap.put("Shyvana", "쉬바나");
        champMap.put("Singed", "신지드");
        champMap.put("Sion", "사이온");
        champMap.put("Sivir", "시비르");
        champMap.put("Skarner", "스카너");
        champMap.put("Smolder", "스몰더");
        champMap.put("Sona", "소나");
        champMap.put("Soraka", "소라카");
        champMap.put("Swain", "스웨인");
        champMap.put("Sylas", "사일러스");
        champMap.put("Syndra", "신드라");
        champMap.put("TahmKench", "탐 켄치");
        champMap.put("Taliyah", "탈리야");
        champMap.put("Talon", "탈론");
        champMap.put("Taric", "타릭");
        champMap.put("Teemo", "티모");
        champMap.put("Thresh", "쓰레쉬");
        champMap.put("Tristana", "트리스타나");
        champMap.put("Trundle", "트런들");
        champMap.put("Tryndamere", "트린다미어");
        champMap.put("TwistedFate", "트위스티드 페이트");
        champMap.put("Twitch", "트위치");
        champMap.put("Udyr", "우디르");
        champMap.put("Urgot", "우르곳");
        champMap.put("Varus", "바루스");
        champMap.put("Vayne", "베인");
        champMap.put("Veigar", "베이가");
        champMap.put("Velkoz", "벨코즈");
        champMap.put("Vex", "벡스");
        champMap.put("Vi", "바이");
        champMap.put("Viego", "비에고");
        champMap.put("Viktor", "빅토르");
        champMap.put("Vladimir", "블라디미르");
        champMap.put("Volibear", "볼리베어");
        champMap.put("Warwick", "워윅");
        champMap.put("Xayah", "자야");
        champMap.put("Xerath", "제라스");
        champMap.put("XinZhao", "신 짜오");
        champMap.put("Yasuo", "야스오");
        champMap.put("Yone", "요네");
        champMap.put("Yorick", "요릭");
        champMap.put("Yuumi", "유미");
        champMap.put("Zac", "자크");
        champMap.put("Zed", "제드");
        champMap.put("Zeri", "제리");
        champMap.put("Ziggs", "직스");
        champMap.put("Zilean", "질리언");
        champMap.put("Zoe", "조이");
        champMap.put("Zyra", "자이라");
    }

    private void initPerkMap() {
        perkIdMap = new HashMap<>();
        perkNameMap = new HashMap<>();

        perkIdMap.put(5008, "적응형 능력치");
        perkIdMap.put(5005, "공격 속도");
        perkIdMap.put(5007, "스킬 가속");
        perkIdMap.put(5010, "이동 속도");
        perkIdMap.put(5001, "레벨 비례 체력");
        perkIdMap.put(5011, "체력");
        perkIdMap.put(5012, "방어력 및 마법 저항력");
        perkIdMap.put(5013, "강인함 및 둔화 저항");
        perkIdMap.put(5002, "방어력");
        perkIdMap.put(5003, "마법 저항력");
        perkIdMap.put(8100, "지배");
        perkIdMap.put(8112, "감전");
        perkIdMap.put(8128, "어둠의 수확");
        perkIdMap.put(9923, "칼날비");
        perkIdMap.put(8126, "비열한 한 방");
        perkIdMap.put(8139, "피의 맛");
        perkIdMap.put(8143, "돌발 일격");
        perkIdMap.put(8136, "좀비 와드");
        perkIdMap.put(8120, "유령 포로");
        perkIdMap.put(8138, "사냥의 증표");
        perkIdMap.put(8135, "보물 사냥꾼");
        perkIdMap.put(8105, "끈질긴 사냥꾼");
        perkIdMap.put(8106, "궁극의 사냥꾼");
        perkIdMap.put(8300, "영감");
        perkIdMap.put(8351, "빙결 강화");
        perkIdMap.put(8360, "봉인 풀린 주문서");
        perkIdMap.put(8369, "선제공격");
        perkIdMap.put(8306, "마법공학 점멸기");
        perkIdMap.put(8304, "마법의 신발");
        perkIdMap.put(8321, "환급");
        perkIdMap.put(8313, "삼중 물약");
        perkIdMap.put(8352, "시간 왜곡 물약");
        perkIdMap.put(8345, "비스킷 배달");
        perkIdMap.put(8347, "우주적 통찰력");
        perkIdMap.put(8410, "쾌속 접근");
        perkIdMap.put(8316, "다재다능");
        perkIdMap.put(8000, "정밀");
        perkIdMap.put(8005, "집중 공격");
        perkIdMap.put(8021, "기민한 발놀림");
        perkIdMap.put(8010, "정복자");
        perkIdMap.put(9101, "생명 흡수");
        perkIdMap.put(9111, "승전보");
        perkIdMap.put(8009, "침착");
        perkIdMap.put(9104, "전설: 민첩함");
        perkIdMap.put(9105, "전설: 가속");
        perkIdMap.put(9103, "전설: 핏빛 길");
        perkIdMap.put(8014, "최후의 일격");
        perkIdMap.put(8017, "체력차 극복");
        perkIdMap.put(8299, "최후의 저항");
        perkIdMap.put(8400, "결의");
        perkIdMap.put(8437, "착취의 손아귀");
        perkIdMap.put(8439, "여진");
        perkIdMap.put(8465, "수호자");
        perkIdMap.put(8446, "철거");
        perkIdMap.put(8463, "생명의 샘");
        perkIdMap.put(8401, "보호막 강타");
        perkIdMap.put(8429, "사전 준비");
        perkIdMap.put(8444, "재생의 바람");
        perkIdMap.put(8473, "뼈 방패");
        perkIdMap.put(8451, "과잉성장");
        perkIdMap.put(8453, "소생");
        perkIdMap.put(8242, "불굴의 의지");
        perkIdMap.put(8200, "마법");
        perkIdMap.put(8214, "콩콩이 소환");
        perkIdMap.put(8229, "신비로운 유성");
        perkIdMap.put(8230, "난입");
        perkIdMap.put(8224, "무효화 구체");
        perkIdMap.put(8226, "마나순환 팔찌");
        perkIdMap.put(8275, "빛의 망토");
        perkIdMap.put(8210, "깨달음");
        perkIdMap.put(8234, "기민함");
        perkIdMap.put(8233, "절대 집중");
        perkIdMap.put(8237, "주문 작열");
        perkIdMap.put(8232, "물 위를 걷는 자");
        perkIdMap.put(8236, "폭풍의 결집");

        perkNameMap.put("지배", "7200_Domination");
        perkNameMap.put("감전", "Domination/Electrocute/Electrocute");
        perkNameMap.put("어둠의 수확", "Domination/DarkHarvest/DarkHarvest");
        perkNameMap.put("칼날비", "Domination/HailOfBlades/HailOfBlades");
        perkNameMap.put("비열한 한 방", "Domination/CheapShot/CheapShot");
        perkNameMap.put("피의 맛", "Domination/TasteOfBlood/GreenTerror_TasteOfBlood");
        perkNameMap.put("돌발 일격", "Domination/SuddenImpact/SuddenImpact");
        perkNameMap.put("좀비 와드", "Domination/ZombieWard/ZombieWard");
        perkNameMap.put("유령 포로", "Domination/GhostPoro/GhostPoro");
        perkNameMap.put("사냥의 증표", "Domination/EyeballCollection/EyeballCollection");
        perkNameMap.put("보물 사냥꾼", "Domination/TreasureHunter/TreasureHunter");
        perkNameMap.put("끈질긴 사냥꾼", "Domination/RelentlessHunter/RelentlessHunter");
        perkNameMap.put("궁극의 사냥꾼", "Domination/UltimateHunter/UltimateHunter");
        perkNameMap.put("영감", "7203_Whimsy");
        perkNameMap.put("빙결 강화", "Inspiration/GlacialAugment/GlacialAugment");
        perkNameMap.put("봉인 풀린 주문서", "Inspiration/UnsealedSpellbook/UnsealedSpellbook");
        perkNameMap.put("선제공격", "Inspiration/FirstStrike/FirstStrike");
        perkNameMap.put("마법공학 점멸기", "Inspiration/HextechFlashtraption/HextechFlashtraption");
        perkNameMap.put("마법의 신발", "Inspiration/MagicalFootwear/MagicalFootwear");
        perkNameMap.put("환급", "Inspiration/CashBack/CashBack2");
        perkNameMap.put("삼중 물약", "Inspiration/PerfectTiming/AlchemistCabinet");
        perkNameMap.put("시간 왜곡 물약", "Inspiration/TimeWarpTonic/TimeWarpTonic");
        perkNameMap.put("비스킷 배달", "Inspiration/BiscuitDelivery/BiscuitDelivery");
        perkNameMap.put("우주적 통찰력", "Inspiration/CosmicInsight/CosmicInsight");
        perkNameMap.put("쾌속 접근", "Resolve/ApproachVelocity/ApproachVelocity");
        perkNameMap.put("다재다능", "Inspiration/JackOfAllTrades/JackofAllTrades2");
        perkNameMap.put("정밀", "7201_Precision");
        perkNameMap.put("집중 공격", "Precision/PressTheAttack/PressTheAttack");
        perkNameMap.put("기민한 발놀림", "Precision/FleetFootwork/FleetFootwork");
        perkNameMap.put("정복자", "Precision/Conqueror/Conqueror");
        perkNameMap.put("생명 흡수", "Precision/AbsorbLife/AbsorbLife");
        perkNameMap.put("승전보", "Precision/Triumph");
        perkNameMap.put("침착", "Precision/PresenceOfMind/PresenceOfMind");
        perkNameMap.put("전설: 민첩함", "Precision/LegendAlacrity/LegendAlacrity");
        perkNameMap.put("전설: 가속", "Precision/LegendHaste/LegendHaste");
        perkNameMap.put("전설: 핏빛 길", "Precision/LegendBloodline/LegendBloodline");
        perkNameMap.put("최후의 일격", "Precision/CoupDeGrace/CoupDeGrace");
        perkNameMap.put("체력차 극복", "Precision/CutDown/CutDown");
        perkNameMap.put("최후의 저항", "Sorcery/LastStand/LastStand");
        perkNameMap.put("결의", "7204_Resolve");
        perkNameMap.put("착취의 손아귀", "Resolve/GraspOfTheUndying/GraspOfTheUndying");
        perkNameMap.put("여진", "Resolve/VeteranAftershock/VeteranAftershock");
        perkNameMap.put("수호자", "Resolve/Guardian/Guardian");
        perkNameMap.put("철거", "Resolve/Demolish/Demolish");
        perkNameMap.put("생명의 샘", "Resolve/FontOfLife/FontOfLife");
        perkNameMap.put("보호막 강타", "Resolve/MirrorShell/MirrorShell");
        perkNameMap.put("사전 준비", "Resolve/Conditioning/Conditioning");
        perkNameMap.put("재생의 바람", "Resolve/SecondWind/SecondWind");
        perkNameMap.put("뼈 방패", "Resolve/BonePlating/BonePlating");
        perkNameMap.put("과잉성장", "Resolve/Overgrowth/Overgrowth");
        perkNameMap.put("소생", "Resolve/Revitalize/Revitalize");
        perkNameMap.put("불굴의 의지", "Sorcery/Unflinching/Unflinching");
        perkNameMap.put("마법", "7202_Sorcery");
        perkNameMap.put("콩콩이 소환", "Sorcery/SummonAery/SummonAery");
        perkNameMap.put("신비로운 유성", "Sorcery/ArcaneComet/ArcaneComet");
        perkNameMap.put("난입", "Sorcery/PhaseRush/PhaseRush");
        perkNameMap.put("무효화 구체", "Sorcery/NullifyingOrb/Pokeshield");
        perkNameMap.put("마나순환 팔찌", "Sorcery/ManaflowBand/ManaflowBand");
        perkNameMap.put("빛의 망토", "Sorcery/NimbusCloak/6361");
        perkNameMap.put("깨달음", "Sorcery/Transcendence/Transcendence");
        perkNameMap.put("기민함", "Sorcery/Celerity/CelerityTemp");
        perkNameMap.put("절대 집중", "Sorcery/AbsoluteFocus/AbsoluteFocus");
        perkNameMap.put("주문 작열", "Sorcery/Scorch/Scorch");
        perkNameMap.put("물 위를 걷는 자", "Sorcery/Waterwalking/Waterwalking");
        perkNameMap.put("폭풍의 결집", "Sorcery/GatheringStorm/GatheringStorm");
    }

    private void initQueueMap() {
        queueMap = new HashMap<>();

        queueMap.put(400, "일반");
        queueMap.put(420, "솔로랭크");
        queueMap.put(430, "일반");
        queueMap.put(440, "자유랭크");
        queueMap.put(450, "칼바람");
        queueMap.put(490, "빠른대전");
        queueMap.put(700, "격전");
        queueMap.put(800, "AI대전");
        queueMap.put(810, "AI대전");
        queueMap.put(820, "AI대전");
        queueMap.put(830, "AI대전");
        queueMap.put(840, "AI대전");
        queueMap.put(850, "AI대전");
        queueMap.put(900, "URF");
        queueMap.put(920, "포로왕");
        queueMap.put(1020, "단일모드");
        queueMap.put(1300, "돌격 넥서스");
        queueMap.put(1400, "궁극기 주문서");
        queueMap.put(1700, "아레나");
        queueMap.put(1710, "아레나");
        queueMap.put(2000, "튜토리얼");
        queueMap.put(2010, "튜토리얼");
        queueMap.put(2020, "튜토리얼");
    }

    private void initSpellMap() {
        spellIdMap = new HashMap<>();
        spellNameMap = new HashMap<>();

        spellIdMap.put(1, "SummonerBoost");
        spellIdMap.put(3, "SummonerExhaust");
        spellIdMap.put(4, "SummonerFlash");
        spellIdMap.put(6, "SummonerHaste");
        spellIdMap.put(7, "SummonerHeal");
        spellIdMap.put(11, "SummonerSmite");
        spellIdMap.put(12, "SummonerTeleport");
        spellIdMap.put(13, "SummonerMana");
        spellIdMap.put(14, "SummonerDot");
        spellIdMap.put(21, "SummonerBarrier");
        spellIdMap.put(30, "SummonerPoroRecall");
        spellIdMap.put(31, "SummonerPoroThrow");
        spellIdMap.put(32, "SummonerSnowball");
        spellIdMap.put(39, "SummonerSnowURFSnowball_Mark");
        spellIdMap.put(54, "Summoner_UltBookPlaceholder");
        spellIdMap.put(55, "Summoner_UltBookSmitePlaceholder");
        spellIdMap.put(2201, "SummonerCherryHold");
        spellIdMap.put(2202, "SummonerCherryFlash");

        spellNameMap.put("SummonerBoost", "정화");
        spellNameMap.put("SummonerExhaust", "탈진");
        spellNameMap.put("SummonerFlash", "점멸");
        spellNameMap.put("SummonerHaste", "유체화");
        spellNameMap.put("SummonerHeal", "회복");
        spellNameMap.put("SummonerSmite", "강타");
        spellNameMap.put("SummonerTeleport", "순간이동");
        spellNameMap.put("SummonerMana", "총명");
        spellNameMap.put("SummonerDot", "점화");
        spellNameMap.put("SummonerBarrier", "SummonerBarrier");
        spellNameMap.put("SummonerPoroRecall", "왕을 향해!");
        spellNameMap.put("SummonerPoroThrow", "포로 던지기");
        spellNameMap.put("SummonerSnowball", "표식");
        spellNameMap.put("SummonerSnowURFSnowball_Mark", "표식");
        spellNameMap.put("Summoner_UltBookPlaceholder", "게임 시작 후 결정");
        spellNameMap.put("Summoner_UltBookSmitePlaceholder", "TBD 및 공격-강타");
        spellNameMap.put("SummonerCherryHold", "도주");
        spellNameMap.put("SummonerCherryFlash", "점멸");
    }

    public String getPerkName(Integer id) {
        return perkIdMap.getOrDefault(id, "");
    }

    public String getPerkUri(String id) {
        return perkNameMap.getOrDefault(id, "");
    }

    public String getSpellId(Integer id) {
        return spellIdMap.getOrDefault(id, "");
    }

    public String getSpellName(String id) {
        return spellNameMap.getOrDefault(id, "");
    }

    public String getQueue(Integer id) {
        return queueMap.getOrDefault(id, "");
    }

    public String getChamp(String id) {
        return champMap.getOrDefault(id, "");
    }

    public String getItem(Integer id) {
        return itemMap.getOrDefault(id, "");
    }

}
